travis:
  secure:
    BINSTAR_TOKEN: XWD+bdRyEb5xzyixJqMPjm/m3KZAoxw1Nikr6cujcteL+bEXwdjIoIJIQiOyVH9TALNXDnYUIn074fEcYu2UMDf3Z6+mByzK2MCk2gj5NzWbBLctCQrSBxy0DUJD1NbVMjLk+kuEESsAjT4Fo6QL08xs4V8sa+GixkGaxtRQj3tJc6STLrPDJO3RXDG12zw5jjGQTsf7/2duAdImwmiBtiV3/YeCkG4fDjjUZF9jYUjcG/bgZZuEswqTtbjaAXnH+sF1NuUMhY+7U78G+rMKhCw86hJHjYGnuD4IYGUuiuLSRYmLSZPMiPRTDa90K2CnxWVw4AIiTL9JD9neDZw7n//02itty0weGGXk9YVjrJysuD+utXoILcwmM3dGZLvFhi338pdL05zwu1PLUSY3fZqUeb6LZENZSlvu1KVK8c6Sp6j/ic1qXOEsXg7j9fMa/fqFTJxi7MOTWAfezSpnfSw9r6T4solFhEdG0kvRfSuh8G5grWXpEZhYUokQZOfBT45tez9uuK81++bqpVvBpyya4GYoFLfsmZGngNbu55v4k1sR0ngypX5bRZsatHDQLydDuyj+H+Isej2qBxMzv1tlKJcw6jaudQZuzPQ/V1P2D2AWz+btXJyuku7GjXErqOT5b4iaSXc0mOBfG8kNGukQwAqHpAAcuhGLF5jU+8c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
